### ISSUE TITLE
Wiki Page about "Folk Tutorial" is not complete

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/ecosystem#46]
The Wiki-Page on folking ends after the fiurst bullet.
We need this description petty urgently because of the relevance to the review process.

**Comment by JonasHelming** [comment]
As this actually a generic topic, there is lots of independant tutorials, e.g. https://help.github.com/articles/fork-a-repo
So I am not sure, if we need a cutom description. what do you think?

**Comment by MERCEmentre** [comment]
No need for specific description. Suggestion: add a link to above doc.

**Comment by mgudemann** [comment]
Good practice to prevent complex merging from old forks seems to be to fork, make changes, do a pull request and then to **delete** the fork after the accepted request. This is also described in the linked tutorial. Nevertheless, deleting a forked repo is a bit strange - you have to go to the _danger zone_ and manually enter the name of the repo.

I suggest to explicitly document this step on the wiki page in addition to the link.

**Comment by BerndHekele** [comment]
Thanks.I News to Special  a Review Prozess and want to make use of the proper building blocks for our project.Can you change the description of this step, please? Or shall I do this little change? Kind RegardsBernd Referent Projekt openETCS I.NVT 321DB Netz AG Völckerstraße 5, 80939 München Tel. +49 89 1308-49543, intern 962 49543-Mobil: +49 171 5616726Matthias Güdemann --- Re: [ecosystem] Wiki Page about "Folk Tutorial" is not complete (#46) --- Von:"Matthias Güdemann" notifications@github.comAn"openETCS/ecosystem" ecosystem@noreply.github.comCc"Bernd Hekele" bernd.hekele@deutschebahn.comDatum:Mi., 13.03.2013 17:40BetreffRe: [ecosystem] Wiki Page about "Folk Tutorial" is not complete (#46)Good practice to prevent complex merging from old forks seems to be to fork, make changes, do a pull request and then to delete the fork after the accepted request. This is also described in the linked tutorial. Nevertheless, deleting a forked repo is a bit strange - you have to go to the danger zone and manually enter the name of the repo.

I suggest to explicitly document this step on the wiki page in addition to the link.

**Comment by JonasHelming** [comment]
I changed the link to the above mentioned documentation.
@Bernd: Could you comment again, the comment is kind of broken.
@mgudemann: Can you do a contribute a mark down page describing what you mentioned?

**Comment by BerndHekele** [comment]
Thanks Jonas.
What exactly do you mean by "broken"

**Comment by mgudemann** [comment]
@JonasHelming 

I tried to directly contribute a Wiki page, but while the wiki pages are also forked, they do not seem to be "pullalbe" to the forked repo. When trying a pull-request, I only get a message that the repos are equivalent.

So here is the markdown code for such a description directly:

<pre>
## Deleting a fork ##
After having merged a single pull-request, it is generally advisable to delete
the fork and re-fork later for another change. This will prevent too much
divergence between the local repository and the project (If you plan to make
many more changes, it is probably better to try to become a committer than to
file pull-requests).
The steps needed to delete a repository are explained here:
https://help.github.com/articles/deleting-a-repository
One should be aware that this is a general procedure to delete any repository
and it not special for forked ones. Therefore, there are some warnings and
obstacles in order to prevent inadvertent deletion. In particular, one has to
navigate to the specially marked **Danger Zone** in the settings of the
repository and has to **manually type** the full name of the repository before
deleting is possible.
</pre>

**Comment by JonasHelming** [comment]
Look great, but please: https://github.com/openETCS/ecosystem/wiki/Contribution-Guidelines
:-)

**Comment by JonasHelming** [comment]
please just paste the declaration here in the comment, I can copy the content form here

**Comment by mgudemann** [comment]
######### SNIP

```
Name: Fork-tutorial wiki page in ecosystem project
Description: Short description how to delete a forked repository after a pull-request has been accepted and is merged.
Gist URL:
Cryptography: No
Author(s): self
```

I hereby declare that I accept to contribute following the openETCS terms of use and the openETCS IP policy.

http://openetcs.org/termsofuse/

https://github.com/openETCS/ecosystem/wiki/IP-Policy
######### SNAP

**Comment by JonasHelming** [comment]
contribution accepted, Thanks!
see https://github.com/openETCS/ecosystem/wiki/Fork%20tutorial
