### ISSUE TITLE
Wrong reference to the Eclipse Committer Form

### ISSUE THREAD

**Issue by KlausRuedigerHase** [openETCS/ecosystem#48]
See at: "Development Resources HOWTO Nominating and Electing a New Committer"
the reference to the openETCS Committerform needs to be corrected.

**Comment by JonasHelming** [comment]
I think all links on that page are pointing to Eclipse documents and therefore need to be corrected. Wo is taking responsibility for the document?

**Comment by BerndHekele** [comment]
As pointed out earlier the document as a whole needs some rework. I will take responsibility for the document.

**Comment by JonasHelming** [comment]
ok, assigned to you

**Comment by BerndHekele** [comment]
@KlausRuedigerHase ,@JonasHelming Do we already have a special openETCS Committer Agreement for individuals?
If not, I propose to crate a new one with the adoptations to openETCS based on the eclipse one.

Since the "Development Resources HOWTO Nominating and Electing a New Committer" document is not finished I propose to replace the document by a new one concentrating on a the different ways to handle the committer paperwork (which in my understanding is very special for openETCS). This new document has toi be linked to the processes. What is your opinion to this approach?

**Comment by JonasHelming** [comment]
I think we have existing committer forms for individuals, please ask Klaus. And I agree, there should be new document...

**Comment by JonasHelming** [comment]
@BerndHekele Have you had the chance to speak to Klaus about this?

**Comment by BerndHekele** [comment]
Yes. It is not only about correcting some wrong formatting. We also need to do some corrections in the definition of the process. We will cover the isse with the charta.
The committer form as such is not an issue, we have an up-to-date version available.

**Comment by JonasHelming** [comment]
OK, can we close this issue then?

**Comment by BerndHekele** [comment]
ok
